export const main = {
    prefix: "!",
    adminTag: "admin",
    trustTag: "trusted",
    notifyTag: "notify",
    developer: "§b@bluemods.lol §7| §3https://dsc.gg/bluemods",
    bmversion: "§gBeta-v5.5.15",
    mcversion: "§g1.21.40",
    bmdescription: "§3This is a beta mode, some of functions may not working with other add-ons. BlueMods AntiCheat for Minecraft Bedrock is a powerful tool designed to protect your server from hackers & cheaters",
    player: "§7<§eplayer§7>",
    reason: "§7[§areason§7]",
    valuedata: "§7<§evalue§7> [§edata§7]",
    addremove: "§7<§aadd§7/§cremove§7>",
    enabledisable: "§7<§aenable§7/§cdisable§7>",
    enabledCommandsKey: "enabledCommands",
    colors: {
        black: "§0",
        dark_blue: "§1",
        dark_green: "§2",
        dark_aqua: "§3",
        dark_red: "§4",
        dark_purple: "§5",
        gold: "§6",
        gray: "§7",
        dark_gray: "§8",
        blue: "§9",
        green: "§a",
        aqua: "§b",
        red: "§c",
        light_purple: "§d",
        yellow: "§e",
        white: "§f" // Default color
    },
    enabledCommands: {
    // General Commands
        "!rtp": false,
        "!help": true,
        "!ping": true,
        "!about": true,
        //"!spawn": true,
        "!home": false,
        "!tpa": true,
    // Gamemodes
        "!gma": true,
        "!gmc": true,
        "!gms": true,
        "!gmsp": true,
        "!vanish": true,
    // Staff Commands
        "!kick": true,
        "!ban": true,
        "!cmdsf": true,
        "!mute": true,
        "!freeze": true,
        "!lagclear": true,
        "!give": true,
        "!troll": true,
        "!welcome": true,
        "!banitem": true,
        "!clearchat": true,
        "!ecwipe": true,
        "!invsee": true,
        "!inwipe": true,
        "!pearl": true,
        "!chatdisplay": true,
        "!rank": true,
    // Operator's Only
        "!notify": true,
        "!op": true,
        "!trusted": true,
    // Development or Beta Testing
        "!incombat": true
    }
};

export default main