# alrights reserve @bluemods.lol - discord account. || please report any bugs or glitches in our discord server https://dsc.gg/bluemods

function globalban/ban

# banned invisibility symbols ===============
tag "§1" add ban
tag "§2" add ban
tag "§3" add ban
tag "§4" add ban
tag "§5" add ban
tag "§6" add ban
tag "§7" add ban
tag "§8" add ban
tag "§9" add ban
tag "§0" add ban

tag "§a" add ban
tag "§b" add ban
tag "§c" add ban
tag "§d" add ban
tag "§e" add ban
tag "§f" add ban
tag "§g" add ban
tag "§h" add ban
tag "§i" add ban
tag "§j" add ban
tag "§k" add ban
tag "§l" add ban
tag "§m" add ban
tag "§n" add ban
tag "§o" add ban
tag "§p" add ban
tag "§q" add ban
tag "§r" add ban
tag "§s" add ban
tag "§t" add ban
tag "§u" add ban
tag "§v" add ban
tag "§w" add ban
tag "§x" add ban
tag "§y" add ban
tag "§z" add ban

tag "§@" add ban
tag "§#" add ban
tag "§$" add ban
tag "§_" add ban
tag "§&" add ban
tag "§-" add ban
tag "§+" add ban
tag "§(" add ban
tag "§)" add ban
tag "§/" add ban
tag "§*" add ban
tag "§'" add ban
tag "§:" add ban
tag "§;" add ban
tag "§!" add ban
tag "§?" add ban
tag "§~" add ban
tag "§`" add ban
tag "§|" add ban
tag "§•" add ban
tag "§√" add ban
tag "§π" add ban
tag "§÷" add ban
tag "§§" add ban
tag "§∆" add ban
tag "§£" add ban
tag "§¢" add ban
tag "§€" add ban
tag "§¥" add ban
tag "§^" add ban
tag "§°" add ban
tag "§=" add ban
tag "§{" add ban
tag "§}" add ban
tag "§%" add ban
tag "§©" add ban
tag "§™" add ban
tag "§✓" add ban
tag "§[" add ban
tag "§]" add ban
tag "§\"" add ban
